In [2]:
import pandas as pd
df = pd.read_csv("../data/raw/lahore_house_listings_zameen.csv")
print(df.shape)
print(df.columns.tolist())

(18249, 23)
['Title', 'Location', 'Type', 'Price', 'Area', 'Bedrooms', 'Bathrooms', 'Purpose', 'Date Posted', 'Built Year', 'Kitchens', 'Store Rooms', 'Servant Quarters', 'Furnished', 'Gym', 'Study Room', 'Drawing Room', 'Dining Room', 'Lawn/Garden', 'Swimming Pool', 'Electricity Backup', 'Lounge/Sitting Room', 'Link']

In [3]:
df.dtypes

Title                      str
Location                   str
Type                       str
Price                      str
Area                       str
Bedrooms                   str
Bathrooms                  str
Purpose                    str
Date Posted                str
Built Year             float64
Kitchens                 int64
Store Rooms              int64
Servant Quarters         int64
Furnished                 bool
Gym                       bool
Study Room                bool
Drawing Room              bool
Dining Room               bool
Lawn/Garden               bool
Swimming Pool             bool
Electricity Backup        bool
Lounge/Sitting Room       bool
Link                       str
dtype: object

In [4]:
df.isnull().sum().sort_values(ascending=False)

Date Posted            6930
Built Year             4752
Title                     0
Furnished                 0
Lounge/Sitting Room       0
Electricity Backup        0
Swimming Pool             0
Lawn/Garden               0
Dining Room               0
Drawing Room              0
Study Room                0
Gym                       0
Store Rooms               0
Servant Quarters          0
Location                  0
Kitchens                  0
Purpose                   0
Bathrooms                 0
Bedrooms                  0
Area                      0
Price                     0
Type                      0
Link                      0
dtype: int64

In [5]:
df.describe()

         Built Year      Kitchens   Store Rooms  Servant Quarters
count  13497.000000  18249.000000  18249.000000      18249.000000
mean    2022.673631      1.679489      0.793742          0.856704
std        4.933459      1.057279      0.784329          1.244107
min     1960.000000      0.000000      0.000000          0.000000
25%     2023.000000      1.000000      0.000000          0.000000
50%     2024.000000      2.000000      1.000000          1.000000
75%     2025.000000      2.000000      1.000000          1.000000
max     2121.000000     32.000000     22.000000        111.000000

In [6]:
display(df["Purpose"].value_counts())
display(df["Type"].value_counts())

Purpose
For Sale    18249
Name: count, dtype: int64

Type
House    18249
Name: count, dtype: int64

In [7]:
display(df[["Price", "Area"]].sample(20))
display(df["Price"].str.split().str[1].value_counts())
display(df["Area"].str.split().str[1].value_counts())

            Price      Area
5975    4.8 Crore  10 Marla
17501   2.1 Crore   5 Marla
2258   1.95 Crore   6 Marla
1539   2.05 Crore   5 Marla
14815     6 Crore   1 Kanal
1784    1.2 Crore   3 Marla
15687   1.5 Crore   4 Marla
17738   1.7 Crore   5 Marla
14994   3.8 Crore  10 Marla
8424   2.45 Crore   5 Marla
457       7 Crore   1 Kanal
16049     75 Lakh   3 Marla
14532     4 Crore  10 Marla
11416   3.3 Crore  10 Marla
15401  4.85 Crore  12 Marla
8260    3.7 Crore  10 Marla
15450     2 Crore   5 Marla
7778    4.5 Crore  10 Marla
11662  5.95 Crore  10 Marla
9282   3.75 Crore   9 Marla

Price
Crore    17451
Lakh       782
Arab        10
Name: count, dtype: int64

Area
Marla    12521
Kanal     5728
Name: count, dtype: int64

In [8]:
display(df['Bedrooms'].value_counts())
display(df['Bathrooms'].value_counts())

Bedrooms
5     6813
3     4571
4     3624
6     1888
7      437
2      321
-      318
8      126
1       60
10      40
9       32
11      19
Name: count, dtype: int64

Bathrooms
6    6804
4    4167
5    3592
3    1533
7    1385
-     420
2     278
1      69
8       1
Name: count, dtype: int64

In [9]:
df.loc[
    (df["Built Year"] > 2026) 
    | (df["Servant Quarters"] > 10) 
    | (df["Store Rooms"] > 10) 
    | (df["Kitchens"] > 10), 
    ['Title', 'Location', 'Built Year', 'Price', 'Area', 'Bedrooms', 'Bathrooms', 'Store Rooms', "Servant Quarters", "Kitchens"]
]

,Title,Location,Built Year,Price,Area,Bedrooms,Bathrooms,Store Rooms,Servant Quarters,Kitchens
184,Affordable Modern Brand New House For Sale In ...,"Central Park - Block A1, Central Park Housing ...",2024.0,1.65 Crore,5 Marla,3,4,1,11,2
434,1 Kanal Very Beautiful Luxury House Urgent for...,"Canal Garden, Lahore, Punjab",2025.0,5.15 Crore,1 Kanal,4,5,0,0,21
568,5 Marla House In Beautiful Location Of Al-Ahma...,"Al-Ahmad Garden Housing Scheme, GT Road, Lahor...",2028.0,1.65 Crore,5 Marla,5,5,1,1,2
613,3 Years Installment Plan Luxury 5 Marla Brand ...,"Park View City, Lahore, Punjab",2029.0,1.65 Crore,5 Marla,4,5,0,0,2
715,5 Marla Fully Furnished Luxury House For Sale,"Bismillah Housing Scheme, GT Road, Lahore, Punjab",2025.0,2.4 Crore,5 Marla,5,6,0,0,21
...,...,...,...,...,...,...,...,...,...,...
17362,3 Marla Used House For Sale In Al-Rehman Garde...,"Al Rehman Garden Phase 2, Al Rehman Garden, La...",2023.0,95 Lakh,3 Marla,2,3,0,12,2
17662,Beautiful House For Sale In Pak Arab With Regi...,"Pak Arab Housing Society Phase 1, Pak Arab Hou...",2028.0,1.8 Crore,4 Marla,3,3,0,0,0
17942,Stunning House Is Available For Sale In Nashem...,"Nasheman-e-Iqbal Phase 2, Nasheman-e-Iqbal, La...",NaN,2.5 Crore,10 Marla,3,3,1,1,32
18031,5 MARLA BEAUTIFUL HOUSE AL - REHMAN GARDEN PHA...,"Al Rehman Garden Phase 2, Al Rehman Garden, La...",2058.0,1.95 Crore,5 Marla,5,6,1,1,2
18120,"4 Kanal House for Sale, Semi Commercial -- Off...",Government Employees Cooperative Housing Socie...,NaN,30 Crore,4 Kanal,6,7,21,3,0

In [10]:
df["Location"].str.contains("Lahore").value_counts()

Location
True    18249
Name: count, dtype: int64

In [11]:
display(df["Kitchens"].value_counts().sort_index())
display(df["Store Rooms"].value_counts().sort_index())
display(df["Servant Quarters"].value_counts().sort_index())
display(df["Built Year"].value_counts().sort_index(ascending= False))

Kitchens
0      2675
1      2501
2     11522
3      1436
4        82
5         9
6         4
7         1
10        1
11        2
21       11
22        3
31        1
32        1
Name: count, dtype: int64

Store Rooms
0     6766
1     8739
2     2612
3      106
4       14
5        3
7        1
8        1
11       3
21       3
22       1
Name: count, dtype: int64

Servant Quarters
0      7153
1      7349
2      3369
3       303
4        36
5        11
6         3
7         3
8         1
11       10
12        6
22        2
23        1
32        1
111       1
Name: count, dtype: int64

Built Year
2121.0       1
2058.0       3
2055.0       1
2029.0       7
2028.0      21
2027.0      20
2026.0      26
2025.0    5862
2024.0    3707
2023.0     927
2022.0     570
2021.0     203
2020.0     488
2019.0     180
2018.0     268
2017.0      92
2016.0      82
2015.0     299
2014.0      72
2013.0      32
2012.0     101
2011.0      34
2010.0     153
2009.0      13
2008.0      20
2007.0      20
2006.0       9
2005.0      56
2004.0      16
2003.0       3
2002.0      13
2001.0      24
2000.0      88
1999.0       8
1998.0       5
1997.0       1
1996.0       2
1995.0      15
1992.0       2
1990.0      39
1988.0       4
1987.0       1
1986.0       4
1980.0       3
1975.0       1
1960.0       1
Name: count, dtype: int64

In [12]:
df_filter = df[
    (
        (df["Built Year"] <= 2028)
        | (df["Built Year"].isnull())
    ) 
    & (df["Kitchens"] <= 6) 
    & (df["Store Rooms"] <= 6) 
    & (df["Servant Quarters"] <= 6)
]

df_filter

,Title,Location,Type,Price,Area,Bedrooms,Bathrooms,Purpose,Date Posted,Built Year,...,Furnished,Gym,Study Room,Drawing Room,Dining Room,Lawn/Garden,Swimming Pool,Electricity Backup,Lounge/Sitting Room,Link
0,ACTUALLY 25 MARLA DOUBLE UNIT LUXURIOUS & GRAC...,"DHA Phase 6 - Block F, DHA Phase 6, DHA Defenc...",House,8.15 Crore,1 Kanal,6,7,For Sale,2025-07-27,2024.0,...,True,True,True,True,True,True,True,True,True,https://www.zameen.com/Property/dha_phase_6_dh...
1,3 Years Installment Plan Luxury Brand New Hous...,"Park View City, Lahore, Punjab",House,1.5 Crore,5 Marla,4,5,For Sale,2025-07-25,2012.0,...,True,False,False,True,True,True,False,True,True,https://www.zameen.com/Property/lahore_park_vi...
2,5 Marla Luxury House In Rose Block Of Park-Vie...,"Park View City - Rose Block, Park View City, L...",House,2.4 Crore,5 Marla,4,4,For Sale,2025-07-25,2025.0,...,True,True,True,True,True,True,True,True,True,https://www.zameen.com/Property/park_view_city...
3,Full Basement 1 kanal Brand New Luxury House N...,"DHA Phase 7 - Block S, DHA Phase 7, DHA Defenc...",House,7.5 Crore,1 Kanal,5,6,For Sale,2025-07-25,2024.0,...,False,True,True,True,True,True,True,True,True,https://www.zameen.com/Property/dha_phase_7_dh...
4,1 Kanal Dream Home With Private Pool In DHA Ph...,"DHA Phase 6, DHA Defence, Lahore, Punjab",House,6.95 Crore,1 Kanal,6,7,For Sale,2025-07-25,2024.0,...,True,True,True,True,True,True,True,True,True,https://www.zameen.com/Property/dha_defence_dh...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18244,3 Years Installment Plan Luxury Brand New Hous...,"Park View City, Lahore, Punjab",House,1.15 Crore,3.5 Marla,4,5,For Sale,2025-07-27,NaN,...,False,False,False,True,True,False,False,False,False,https://www.zameen.com/Property/lahore_park_vi...
18245,3 Years Installment Plan Luxury Brand New Hous...,"Park View City, Lahore, Punjab",House,1.15 Crore,3.5 Marla,3,4,For Sale,NaN,2025.0,...,True,True,True,True,True,False,False,True,True,https://www.zameen.com/Property/lahore_park_vi...
18246,3 Years Installment Plan Luxury Brand New Hous...,"Park View City, Lahore, Punjab",House,1.1 Crore,3.5 Marla,4,5,For Sale,NaN,2024.0,...,True,True,True,True,True,False,False,True,True,https://www.zameen.com/Property/lahore_park_vi...
18247,3 Years Installment Plan Luxury Brand New Hous...,"Park View City, Lahore, Punjab",House,1.1 Crore,3.5 Marla,3,4,For Sale,2025-07-28,NaN,...,False,False,False,True,True,False,False,False,False,https://www.zameen.com/Property/lahore_park_vi...
18248,CUTTING-EDGE-DESIGN,"DHA Phase 6, DHA Defence, Lahore, Punjab",House,2.3 Crore,5 Marla,4,5,For Sale,2025-07-29,2024.0,...,False,False,False,False,False,False,False,True,False,https://www.zameen.com/Property/dha_defence_dh...

In [13]:
display(df.shape)
df_filter.shape

(18249, 23)

(18183, 23)

In [14]:
price_split = df_filter["Price"].str.split(expand=True)
price_split[1].isnull().value_counts()

1
False    18177
True         6
Name: count, dtype: int64

In [15]:
missing_unit_mask = price_split[1].isnull()
df_filter = df_filter[~missing_unit_mask]

In [16]:
price_num = pd.to_numeric(price_split[0])

price_mapping = {
    "Crore": 10_000_000,
    "Lakh": 100_000,
    "Arab": 1_000_000_000
}

price_multiplier = price_split[1].map(price_mapping)

price_pkr = price_num * price_multiplier

df_filter["Price_PKR"] = price_pkr
df_filter["Price_PKR"].isnull().sum()

np.int64(0)

In [17]:
area_split = df_filter["Area"].str.split(expand=True)
display(area_split.isnull().sum())

area_num = pd.to_numeric(area_split[0])

area_mapping = {
    "Marla": 1,
    "Kanal": 20,
}

area_multiplier = area_split[1].map(area_mapping)

area_Marla = area_num * area_multiplier

df_filter["Area_Marla"] = area_Marla

df_filter[["Area_Marla", "Area"]]

0    0
1    0
dtype: int64

       Area_Marla       Area
0            20.0    1 Kanal
1             5.0    5 Marla
2             5.0    5 Marla
3            20.0    1 Kanal
4            20.0    1 Kanal
...           ...        ...
18244         3.5  3.5 Marla
18245         3.5  3.5 Marla
18246         3.5  3.5 Marla
18247         3.5  3.5 Marla
18248         5.0    5 Marla

[18177 rows x 2 columns]

In [18]:
df_filter[["Price_PKR", "Area_Marla"]].describe()

          Price_PKR    Area_Marla
count  1.817700e+04  18177.000000
mean   5.858330e+07     12.510794
std    8.037488e+07     12.808574
min    1.490000e+06      0.000000
25%    2.050000e+07      5.000000
50%    3.550000e+07     10.000000
75%    7.120000e+07     20.000000
max    2.000000e+09    480.000000

In [19]:
df_filter = df_filter[df_filter["Area_Marla"] != 0]
print(df_filter.shape)

(18175, 25)

In [20]:
print(df_filter.shape)
print(df_filter.columns.tolist())

(18175, 25)
['Title', 'Location', 'Type', 'Price', 'Area', 'Bedrooms', 'Bathrooms', 'Purpose', 'Date Posted', 'Built Year', 'Kitchens', 'Store Rooms', 'Servant Quarters', 'Furnished', 'Gym', 'Study Room', 'Drawing Room', 'Dining Room', 'Lawn/Garden', 'Swimming Pool', 'Electricity Backup', 'Lounge/Sitting Room', 'Link', 'Price_PKR', 'Area_Marla']

In [21]:
bins = [1959, 2015, 2020, 2023, 2025, 2031]
labels = ['Pre-2015', '2015-2020', '2021-2023', '2024-2025', '2026+']
df_filter['Built_Year_Bucket'] = pd.cut(df_filter['Built Year'], bins=bins, labels=labels)
display(df_filter.groupby('Built_Year_Bucket')['Price_PKR'].agg(['count', 'mean', 'median']))
display(df_filter[df_filter['Built Year'].isnull()]['Price_PKR'].describe())
df_filter[df_filter['Built Year'].notnull()]['Price_PKR'].describe()

                   count          mean      median
Built_Year_Bucket
Pre-2015            1035  7.989990e+07  46000000.0
2015-2020           1103  5.483046e+07  38000000.0
2021-2023           1691  5.804023e+07  35000000.0
2024-2025           9537  6.039035e+07  38000000.0
2026+                 67  4.186119e+07  26500000.0

count    4.742000e+03
mean     5.161637e+07
std      8.085836e+07
min      3.300000e+06
25%      1.850000e+07
50%      3.000000e+07
75%      5.657500e+07
max      2.000000e+09
Name: Price_PKR, dtype: float64

count    1.343300e+04
mean     6.104875e+07
std      8.006615e+07
min      1.490000e+06
25%      2.100000e+07
50%      3.850000e+07
75%      7.500000e+07
max      2.000000e+09
Name: Price_PKR, dtype: float64

In [22]:
df_filter.groupby('Built_Year_Bucket')['Area_Marla'].agg(['count', 'mean', 'median'])

                   count       mean  median
Built_Year_Bucket
Pre-2015            1035  17.423865    10.0
2015-2020           1103  13.070354    10.0
2021-2023           1691  12.783974    10.0
2024-2025           9537  12.470997    10.0
2026+                 67   9.173134     5.0

In [23]:
median_year = df_filter['Built Year'].median()

df_filter['Built_Year_Missing'] = df_filter['Built Year'].isnull().astype(int)
df_filter['Built Year'] = df_filter['Built Year'].fillna(median_year)

In [24]:
display(df_filter['Built Year'].isnull().sum())
df_filter['Built_Year_Missing'].value_counts()

np.int64(0)

Built_Year_Missing
0    13433
1     4742
Name: count, dtype: int64

In [25]:
df_filter

,Title,Location,Type,Price,Area,Bedrooms,Bathrooms,Purpose,Date Posted,Built Year,...,Dining Room,Lawn/Garden,Swimming Pool,Electricity Backup,Lounge/Sitting Room,Link,Price_PKR,Area_Marla,Built_Year_Bucket,Built_Year_Missing
0,ACTUALLY 25 MARLA DOUBLE UNIT LUXURIOUS & GRAC...,"DHA Phase 6 - Block F, DHA Phase 6, DHA Defenc...",House,8.15 Crore,1 Kanal,6,7,For Sale,2025-07-27,2024.0,...,True,True,True,True,True,https://www.zameen.com/Property/dha_phase_6_dh...,81500000.0,20.0,2024-2025,0
1,3 Years Installment Plan Luxury Brand New Hous...,"Park View City, Lahore, Punjab",House,1.5 Crore,5 Marla,4,5,For Sale,2025-07-25,2012.0,...,True,True,False,True,True,https://www.zameen.com/Property/lahore_park_vi...,15000000.0,5.0,Pre-2015,0
2,5 Marla Luxury House In Rose Block Of Park-Vie...,"Park View City - Rose Block, Park View City, L...",House,2.4 Crore,5 Marla,4,4,For Sale,2025-07-25,2025.0,...,True,True,True,True,True,https://www.zameen.com/Property/park_view_city...,24000000.0,5.0,2024-2025,0
3,Full Basement 1 kanal Brand New Luxury House N...,"DHA Phase 7 - Block S, DHA Phase 7, DHA Defenc...",House,7.5 Crore,1 Kanal,5,6,For Sale,2025-07-25,2024.0,...,True,True,True,True,True,https://www.zameen.com/Property/dha_phase_7_dh...,75000000.0,20.0,2024-2025,0
4,1 Kanal Dream Home With Private Pool In DHA Ph...,"DHA Phase 6, DHA Defence, Lahore, Punjab",House,6.95 Crore,1 Kanal,6,7,For Sale,2025-07-25,2024.0,...,True,True,True,True,True,https://www.zameen.com/Property/dha_defence_dh...,69500000.0,20.0,2024-2025,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18244,3 Years Installment Plan Luxury Brand New Hous...,"Park View City, Lahore, Punjab",House,1.15 Crore,3.5 Marla,4,5,For Sale,2025-07-27,2024.0,...,True,False,False,False,False,https://www.zameen.com/Property/lahore_park_vi...,11500000.0,3.5,NaN,1
18245,3 Years Installment Plan Luxury Brand New Hous...,"Park View City, Lahore, Punjab",House,1.15 Crore,3.5 Marla,3,4,For Sale,NaN,2025.0,...,True,False,False,True,True,https://www.zameen.com/Property/lahore_park_vi...,11500000.0,3.5,2024-2025,0
18246,3 Years Installment Plan Luxury Brand New Hous...,"Park View City, Lahore, Punjab",House,1.1 Crore,3.5 Marla,4,5,For Sale,NaN,2024.0,...,True,False,False,True,True,https://www.zameen.com/Property/lahore_park_vi...,11000000.0,3.5,2024-2025,0
18247,3 Years Installment Plan Luxury Brand New Hous...,"Park View City, Lahore, Punjab",House,1.1 Crore,3.5 Marla,3,4,For Sale,2025-07-28,2024.0,...,True,False,False,False,False,https://www.zameen.com/Property/lahore_park_vi...,11000000.0,3.5,NaN,1
18248,CUTTING-EDGE-DESIGN,"DHA Phase 6, DHA Defence, Lahore, Punjab",House,2.3 Crore,5 Marla,4,5,For Sale,2025-07-29,2024.0,...,False,False,False,True,False,https://www.zameen.com/Property/dha_defence_dh...,23000000.0,5.0,2024-2025,0

In [26]:
df_filter['Bedrooms'] = pd.to_numeric(df_filter['Bedrooms'], errors='coerce')
df_filter['Bathrooms'] = pd.to_numeric(df_filter['Bathrooms'], errors='coerce')

df_filter['Bedrooms'] = df_filter['Bedrooms'].fillna(df_filter['Bedrooms'].median())
df_filter['Bathrooms'] = df_filter['Bathrooms'].fillna(df_filter['Bathrooms'].median())

In [27]:
display(df["Location"].nunique())
df_filter.columns.tolist()

1304

['Title',
 'Location',
 'Type',
 'Price',
 'Area',
 'Bedrooms',
 'Bathrooms',
 'Purpose',
 'Date Posted',
 'Built Year',
 'Kitchens',
 'Store Rooms',
 'Servant Quarters',
 'Furnished',
 'Gym',
 'Study Room',
 'Drawing Room',
 'Dining Room',
 'Lawn/Garden',
 'Swimming Pool',
 'Electricity Backup',
 'Lounge/Sitting Room',
 'Link',
 'Price_PKR',
 'Area_Marla',
 'Built_Year_Bucket',
 'Built_Year_Missing']

In [28]:
df_features = df_filter[["Location", "Area_Marla", "Bedrooms", "Bathrooms", "Built Year", 
                         "Kitchens", "Store Rooms", "Servant Quarters",]]

In [29]:
df_filter = df_filter[df_filter["Built Year"] < 2026]

In [30]:
first_part = df_features["Location"].str.split(",").str[0]
second_part = df_features["Location"].str.split(",").str[1].str.strip()
condition = first_part.str.contains(" - ")

In [31]:
import numpy as np

df_features["Location_Clean"] = np.where(condition, second_part, first_part)
df_features[["Location", "Location_Clean"]].sample(10, random_state=42)

,Location,Location_Clean
737,"Central Park - Block G, Central Park Housing S...",Central Park Housing Scheme
11102,"DHA Phase 6, DHA Defence, Lahore, Punjab",DHA Phase 6
14076,"DHA 9 Town, DHA Defence, Lahore, Punjab",DHA 9 Town
4295,"DHA Phase 6, DHA Defence, Lahore, Punjab",DHA Phase 6
12450,"Askari 10, Askari, Lahore, Punjab",Askari 10
12770,"DHA 11 Rahbar Phase 2 Extension - Block N, DHA...",DHA 11 Rahbar Phase 2 Extension
8945,"DHA Phase 5 - Block E, DHA Phase 5, DHA Defenc...",DHA Phase 5
17364,"DHA Phase 7 - Block U, DHA Phase 7, DHA Defenc...",DHA Phase 7
17989,"Bahria Town - Jinnah Block, Bahria Town - Sect...",Bahria Town - Sector E
6078,"DHA Phase 6, DHA Defence, Lahore, Punjab",DHA Phase 6

In [32]:
df_features["Location_Clean"].nunique()

568

In [33]:
df_features["Location_Clean"].value_counts().tail(20)

Location_Clean
Firdous Market          1
Qadri Colony            1
Baghbanpura             1
UMT Society             1
Divine Homes            1
Sarwar Colony           1
Ismail Town             1
Bagh Gul Begum          1
Rahat Park              1
Union Park              1
Nadeem Shaheed Road     1
Abbas Block             1
Emerald City            1
Mohafiz Town Phase 1    1
Salamatpura             1
Cantt View Society      1
GOR 1                   1
Makkah Colony           1
Canal View Block E      1
Canal Burg              1
Name: count, dtype: int64

In [34]:
location_counts = df_features["Location_Clean"].value_counts()

common_locations = location_counts[location_counts >= 20].index

df_features["Location_Clean"] = np.where(
    df_features["Location_Clean"].isin(common_locations),
    df_features["Location_Clean"],
    "Other"
)

print(df_features["Location_Clean"].nunique())
df_features["Location_Clean"].value_counts().head(20)

118

Location_Clean
Other                          1815
DHA Phase 6                    1764
DHA Phase 7                    1512
Park View City                  973
DHA 9 Town                      743
Bahria Town                     652
DHA Phase 5                     606
Central Park Housing Scheme     388
DHA Phase 8                     378
Bahria Town - Sector C          329
Lake City                       324
Al Rehman Garden Phase 2        319
Paragon City                    303
Valencia Housing Society        271
DHA Phase 3                     258
Bahria Town - Sector E          257
DHA Phase 4                     249
Wapda Town Phase 1              218
DHA 11 Rahbar Phase 2           187
Allama Iqbal Town               185
Name: count, dtype: int64

In [35]:
df_model = pd.get_dummies(
    df_features,
    columns=["Location_Clean"],
    dtype=int
)

print(df_model.shape)
df_model.head()

(18175, 126)

,Location,Area_Marla,Bedrooms,Bathrooms,Built Year,Kitchens,Store Rooms,Servant Quarters,Location_Clean_AWT Phase 2,Location_Clean_Al Hafeez Gardens,...,Location_Clean_Sabzazar Scheme,Location_Clean_Samanabad,Location_Clean_Shadab Garden,Location_Clean_Tajpura,Location_Clean_Tariq Gardens,Location_Clean_Township,Location_Clean_UET Housing Society,Location_Clean_Valencia Housing Society,Location_Clean_Wapda Town,Location_Clean_Wapda Town Phase 1
0,"DHA Phase 6 - Block F, DHA Phase 6, DHA Defenc...",20.0,6.0,7.0,2024.0,3,2,2,0,0,...,0,0,0,0,0,0,0,0,0,0
1,"Park View City, Lahore, Punjab",5.0,4.0,5.0,2012.0,2,1,3,0,0,...,0,0,0,0,0,0,0,0,0,0
2,"Park View City - Rose Block, Park View City, L...",5.0,4.0,4.0,2025.0,2,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,"DHA Phase 7 - Block S, DHA Phase 7, DHA Defenc...",20.0,5.0,6.0,2024.0,2,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,"DHA Phase 6, DHA Defence, Lahore, Punjab",20.0,6.0,7.0,2024.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [37]:
df_model.to_csv("../data/processed/cleaned_houses.csv", index=False)