# Pakistan Real Estate Price Predictor
## Part 2: Model Training

In [2]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

import joblib

In [3]:
df = pd.read_csv("../data/processed/cleaned_houses.csv")

In [4]:
X = df.drop(columns=["Price_PKR", "Location"])
y = df["Price_PKR"]

print(X.shape, y.shape)
X

(18175, 125) (18175,)

,Area_Marla,Bedrooms,Bathrooms,Built Year,Kitchens,Store Rooms,Servant Quarters,Location_Clean_AWT Phase 2,Location_Clean_Al Hafeez Gardens,Location_Clean_Al Haram Garden,...,Location_Clean_Sabzazar Scheme,Location_Clean_Samanabad,Location_Clean_Shadab Garden,Location_Clean_Tajpura,Location_Clean_Tariq Gardens,Location_Clean_Township,Location_Clean_UET Housing Society,Location_Clean_Valencia Housing Society,Location_Clean_Wapda Town,Location_Clean_Wapda Town Phase 1
0,20.0,6.0,7.0,2024.0,3,2,2,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,5.0,4.0,5.0,2012.0,2,1,3,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,5.0,4.0,4.0,2025.0,2,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,20.0,5.0,6.0,2024.0,2,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,20.0,6.0,7.0,2024.0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18170,3.5,4.0,5.0,2024.0,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18171,3.5,3.0,4.0,2025.0,2,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18172,3.5,4.0,5.0,2024.0,2,2,2,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18173,3.5,3.0,4.0,2024.0,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18174,5.0,4.0,5.0,2024.0,2,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [6]:
print(
    X_train.shape,
    X_test.shape,
    y_train.shape,
    y_test.shape,
)

(14540, 125) (3635, 125) (14540,) (3635,)

In [7]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [8]:
model.intercept_

np.float64(-423191810.6603602)

In [9]:
len(model.coef_)

125

In [10]:
y_pred = model.predict(X_test)

In [11]:
y_pred.shape

(3635,)

In [12]:
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

In [13]:
print(mae)
print(rmse)
print(r2)

18863243.551085833
42351131.4344859
0.7282067991055627

In [14]:
comparison = pd.DataFrame({
    "Actual": y_test.reset_index(drop=True),
    "Predicted": y_pred,
})

comparison.head()

        Actual     Predicted
0   35500000.0  4.842338e+07
1   25500000.0  6.104001e+07
2   25000000.0  2.200694e+07
3  250000000.0  2.174445e+08
4   87500000.0  8.690876e+07

In [15]:
joblib.dump(model, "../models/linear_regression.joblib")

['../models/linear_regression.joblib']

In [16]:
loaded_model = joblib.load("../models/linear_regression.joblib")

In [17]:
loaded_model.predict(X_test) == model.predict(X_test)

array([ True,  True,  True, ...,  True,  True,  True], shape=(3635,))

In [18]:
feature_columns = X_train.columns.tolist()
joblib.dump(feature_columns, "../models/feature_columns.joblib")

['../models/feature_columns.joblib']

In [19]:
feature_columns

['Area_Marla',
 'Bedrooms',
 'Bathrooms',
 'Built Year',
 'Kitchens',
 'Store Rooms',
 'Servant Quarters',
 'Location_Clean_AWT Phase 2',
 'Location_Clean_Al Hafeez Gardens',
 'Location_Clean_Al Haram Garden',
 'Location_Clean_Al Jalil Garden',
 'Location_Clean_Al Rehman Garden Phase 2',
 'Location_Clean_Al-Ahmad Garden Housing Scheme',
 'Location_Clean_Al-Kabir Town',
 'Location_Clean_Al-Kabir Town - Phase 2',
 'Location_Clean_Allama Iqbal Town',
 'Location_Clean_Architects Engineers Housing Society',
 'Location_Clean_Askari 10',
 'Location_Clean_Askari 11',
 'Location_Clean_Askari 5',
 'Location_Clean_Audit & Accounts Phase 1',
 'Location_Clean_Bahria Nasheman',
 'Location_Clean_Bahria Orchard',
 'Location_Clean_Bahria Orchard Phase 1',
 'Location_Clean_Bahria Orchard Phase 2',
 'Location_Clean_Bahria Orchard Phase 4',
 'Location_Clean_Bahria Town',
 'Location_Clean_Bahria Town - Overseas Enclave',
 'Location_Clean_Bahria Town - Sector B',
 'Location_Clean_Bahria Town - Sector C',
 'Location_Clean_Bahria Town - Sector D',
 'Location_Clean_Bahria Town - Sector E',
 'Location_Clean_Bahria Town - Sector F',
 'Location_Clean_Bankers Avenue Cooperative Housing Society',
 'Location_Clean_Bankers Co-operative Housing Society',
 'Location_Clean_Bedian Road',
 'Location_Clean_Bismillah Housing Scheme',
 'Location_Clean_Canal Bank Housing Scheme',
 'Location_Clean_Canal Garden',
 'Location_Clean_Cantt',
 'Location_Clean_Cavalry Extension',
 'Location_Clean_Cavalry Ground',
 'Location_Clean_Central Park Housing Scheme',
 'Location_Clean_Chinar Bagh',
 'Location_Clean_DHA 11 Rahbar',
 'Location_Clean_DHA 11 Rahbar Phase 1',
 'Location_Clean_DHA 11 Rahbar Phase 2',
 'Location_Clean_DHA 9 Town',
 'Location_Clean_DHA Phase 1',
 'Location_Clean_DHA Phase 2',
 'Location_Clean_DHA Phase 3',
 'Location_Clean_DHA Phase 4',
 'Location_Clean_DHA Phase 5',
 'Location_Clean_DHA Phase 6',
 'Location_Clean_DHA Phase 7',
 'Location_Clean_DHA Phase 8',
 'Location_Clean_Defence Raya',
 'Location_Clean_Divine Gardens',
 'Location_Clean_Dream Gardens',
 'Location_Clean_EME Society',
 'Location_Clean_Eden Avenue',
 'Location_Clean_Eden Boulevard Housing Scheme',
 'Location_Clean_Eden City',
 'Location_Clean_Elite Town',
 'Location_Clean_Etihad Town Phase 1',
 'Location_Clean_Faisal Town',
 'Location_Clean_Fazaia Housing Scheme Phase 1',
 'Location_Clean_Ferozepur Road',
 'Location_Clean_Formanites Housing Scheme',
 'Location_Clean_Garden Town',
 'Location_Clean_Green City',
 'Location_Clean_Gulberg',
 'Location_Clean_Gulberg 2',
 'Location_Clean_Gulberg 3',
 'Location_Clean_Gulshan-e-Ravi',
 'Location_Clean_Hamza Town Phase 2',
 'Location_Clean_IEP Engineers Town',
 'Location_Clean_IEP Engineers Town - Sector A',
 'Location_Clean_Johar Town',
 'Location_Clean_Johar Town Phase 1',
 'Location_Clean_Johar Town Phase 2',
 'Location_Clean_Jubilee Town',
 'Location_Clean_Khayaban-e-Amin',
 'Location_Clean_Khuda Buksh Colony',
 'Location_Clean_LDA Avenue',
 'Location_Clean_Lahore',
 'Location_Clean_Lahore Medical Housing Society',
 'Location_Clean_Lahore Motorway City',
 'Location_Clean_Lake City',
 'Location_Clean_Lake City - Sector M-7',
 'Location_Clean_Lake City Meadows',
 'Location_Clean_Lake City Meadows Phase 1',
 'Location_Clean_Low Cost Sector',
 'Location_Clean_Main Canal Bank Road',
 'Location_Clean_Marghzar Officers Colony',
 'Location_Clean_Military Accounts Housing Society',
 'Location_Clean_Model Town',
 'Location_Clean_NFC 1',
 'Location_Clean_Nasheman-e-Iqbal Phase 2',
 'Location_Clean_New Lahore City',
 'Location_Clean_Nishtar Colony',
 'Location_Clean_OPF Housing Scheme',
 'Location_Clean_Other',
 'Location_Clean_Overseas Low Cost',
 'Location_Clean_PAF Falcon Complex',
 'Location_Clean_PCSIR Housing Scheme Phase 2',
 'Location_Clean_PCSIR Staff Colony',
 'Location_Clean_PGECHS Phase 2',
 'Location_Clean_PIA Housing Scheme',
 'Location_Clean_Pak Arab Housing Society',
 'Location_Clean_Pak Arab Housing Society Phase 1',
 'Location_Clean_Paragon City',
 'Location_Clean_Park View City',
 'Location_Clean_Punjab Coop Housing Society',
 'Location_Clean_Punjab University Society Phase 2',
 'Location_Clean_Sabzazar Scheme',
 'Location_Clean_Samanabad',
 'Location_Clean_Shadab Garden',
 'Location_Clean_Tajpura',
 'Location_Clean_Tariq Gardens',
 'Location_Clean_Township',
 'Location_Clean_UET Housing Society',
 'Location_Clean_Valencia Housing Society',
 'Location_Clean_Wapda Town',
 'Location_Clean_Wapda Town Phase 1']

In [23]:
for location in [
    "AWT Phase 2",
    "DHA Phase 6",
    "Bahria Town",
    "Johar Town"
]:
    feature_dict = {col: 0 for col in feature_columns}

    feature_dict["Area_Marla"] = 5
    feature_dict["Bedrooms"] = 3
    feature_dict["Bathrooms"] = 3
    feature_dict["Built Year"] = 2025
    feature_dict["Kitchens"] = 1
    feature_dict["Store Rooms"] = 1
    feature_dict["Servant Quarters"] = 0

    col = f"Location_Clean_{location}"

    if col in feature_dict:
        feature_dict[col] = 1
    else:
        feature_dict["Location_Clean_Other"] = 1

    pred = model.predict(pd.DataFrame([feature_dict]))[0]

    print(location, pred)

AWT Phase 2 -11957460.757827401
DHA Phase 6 60674355.23590106
Bahria Town 14410583.57300651
Johar Town 18231030.517441154